voter/urls.py
from django.conf.urls import url, include

from voter.views import main, user, vote, asyncx

app_name = 'voter'

async_patterns = [
    url(r'^all-my-votes$', asyncx.get_all_my_votes, name='async-all-my-votes'),
    url(r'^all-names$', asyncx.get_all_names, name='async-all-names'),
    url(r'^my-best-names$', asyncx.get_my_best_names, name='async-my-best-names'),
    url(r'^common-best-names$', asyncx.get_common_best_names, name='async-common-best-names'),
    url(r'^common-total-names$', asyncx.get_common_total_names, name='async-common-total-names')
]

urlpatterns = [
    url(r'^$', main.index, name='index'),
    url(r'^login$', user.user_login, name='login'),
    url(r'^logout$', user.user_logout, name='logout'),
    url(r'^signup$', user.user_signup, name='signup'),
    url(r'^skin/change$', user.skin_change, name='skin-change'),
    url(r'^child/change$', user.child_change, name='child-change'),
    url(r'^child/save$', user.child_save, name='child-save'),
    url(r'^vote/(?P<type>first-round|second-round|random|change)$', vote.index, name='vote'),
    url(r'^vote/save$', vote.save, name='vote-save'),
    url(r'^async/', include(async_patterns)),
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

ynamer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('voter.urls')),
    url(r'^admin/', admin.site.urls),
]

voter/forms/child.py
from django import forms
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from voter.models import Child, Family


class ChildForm(forms.Form):
    family_id = forms.CharField(
        widget=forms.HiddenInput()
    )
    title = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Code name / title'),
                'aria-describedby': 'child-title-icon'
            }
        )
    )
    sex = forms.ChoiceField(
        choices=Child.SEX_TYPES,
        widget=forms.RadioSelect()
    )

    def save(self):
        child = Child(
            title=self.cleaned_data['title'],
            sex=self.cleaned_data['sex'],
            family=Family.objects.get(id=self.cleaned_data['family_id']),
            created_at=timezone.now()
        )
        child.save()

voter/forms/login.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from django import forms


class LoginForm(forms.Form):
    user = None
    username = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Username'),
                'aria-describedby': 'login-username-icon'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'aria-describedby': 'login-password-icon'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        user = authenticate(
            username=cleaned_data['username'],
            password=cleaned_data['password']
        )
        if user is None:
            raise forms.ValidationError(_('User not found. Try again, or sign up!'))
        else:
            self.user = user

voter/views/asyncx.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from voter.models import Vote, VoteLog, ChildName, Child, Family
from voter.helpers.session import SessionHelper


def __init(request):
    response = None

    if not request.user.is_authenticated:
        response = HttpResponse('Unauthorized', status=401)

    active_child_id = request.session.get(SessionHelper.KEY_ACTIVE_CHILD_ID, None)
    if active_child_id is None:
        response = HttpResponse('Forbidden', status=403)

    return response is None, active_child_id, response


def get_my_best_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    my_best_names = Vote.objects.filter(
        user_id=request.user.id,
        score__gt=Vote.SCORE_WHY_NOT,
        child_id=active_child_id
    ).order_by('-score')

    params = {
        'my_best_names': my_best_names
    }

    return render_to_response('voter/async/my-best-names.html', params)


def get_all_my_votes(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    my_votes = VoteLog.objects.filter(user_id=request.user.id, child_id=active_child_id).order_by('-created_at')

    params = {
        'my_votes': my_votes
    }

    return render_to_response('voter/async/all-my-votes.html', params)


def get_all_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    active_child = Child.objects.get(id=active_child_id)
    all_names_with_score = ChildName.get_all_with_vote(user=request.user, child=active_child)

    params = {
        'names': all_names_with_score
    }

    return render_to_response('voter/async/all-names-with-score.html', params)


def get_common_best_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    active_child = Child.objects.get(id=active_child_id)
    family = Family.get_by_user(request.user)
    spouse = family.get_other_user(user=request.user)

    common_best_names = ChildName.get_common_best_list(user=request.user, spouse=spouse, child=active_child)

    params = {
        'common_best_names': common_best_names
    }

    return render_to_response('voter/async/common-best-names.html', params)


def get_common_total_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    active_child = Child.objects.get(id=active_child_id)
    family = Family.get_by_user(request.user)
    spouse = family.get_other_user(user=request.user)

    common_total_names = ChildName.get_common_total_list(user=request.user, spouse=spouse, child=active_child)

    params = {
        'user': request.user,
        'spouse': spouse,
        'common_total_names': common_total_names
    }

    return render_to_response('voter/async/common-total-names.html', params)

voter/views/user.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout
from voter.models import Child, Family
from voter.forms.login import LoginForm
from voter.forms.signup import SignupForm
from voter.forms.child import ChildForm
from voter.helpers.session import SessionHelper
from voter.helpers.skin import SkinHelper
from voter.helpers.cookie import CookieHelper


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)

        if login_form.is_valid():
            login(request, login_form.user)
            return redirect(reverse('voter:index'))
    else:
        login_form = LoginForm()

    params = {
        'login_form': login_form
    }

    return render(request, 'voter/login.html', params)


def user_logout(request):
    logout(request)
    return redirect(reverse('voter:login'))


def user_signup(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)

        if signup_form.is_valid():
            signup_form.signup()
            # TODO implement success message
            return redirect(reverse('voter:login'))
    else:
        signup_form = SignupForm()

    params = {
        'signup_form': signup_form
    }

    return render(request, 'voter/signup.html', params)


def child_change(request):
    if request.method != 'POST' or not request.user.is_authenticated:
        return redirect(reverse('voter:index'))

    selected_child_id = request.POST.get('selected_child_id', None)
    family = Family.get_by_user(request.user)

    try:
        Child.objects.get(id=selected_child_id, family=family)
        request.session.update({
            SessionHelper.KEY_ACTIVE_CHILD_ID: int(selected_child_id)
        })
    except Child.DoesNotExist:
        # TODO error handling
        pass

    return redirect(reverse('voter:index'))


def child_save(request):
    if request.method != 'POST' or not request.user.is_authenticated:
        return redirect(reverse('voter:index'))

    child_form = ChildForm(request.POST)
    if child_form.is_valid():
        child_form.save()

    return redirect(reverse('voter:index'))


def skin_change(request):
    skin = request.GET.get('s', None)

    response = redirect(reverse('voter:index'))

    if skin in SkinHelper.AVAILABLE_SKINS:
        response.set_cookie(CookieHelper.KEY_SELECTED_SKIN, skin, CookieHelper.TTL_SELECTED_SKIN)

    return response

voter/views/vote.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.middleware import csrf
from random import randint
from voter.models import ChildName, Vote, Family, Child, VoteLog
from voter.helpers.vote import VoteHelper
from voter.helpers.session import SessionHelper


@csrf_exempt
def index(request, type=None):
    index_url = reverse('voter:index')

    active_child_id = request.session.get(SessionHelper.KEY_ACTIVE_CHILD_ID, None)
    language_code = request.session.get(SessionHelper.KEY_FAMILY_LANGUAGE_CODE, None)
    if not request.user.is_authenticated or active_child_id is None or language_code is None:
        return redirect(index_url)

    active_child = Child.objects.get(id=active_child_id)
    change_child_name_id = request.POST.get('child_name_id', None)
    is_step_back = bool(request.POST.get('step_back', False))
    previous_type = request.POST.get('previous_type', None)
    previous_child_name_id = request.session.get(SessionHelper.KEY_LAST_VOTE_CHILD_NAME_ID, None)

    if previous_child_name_id:
        del request.session[SessionHelper.KEY_LAST_VOTE_CHILD_NAME_ID]

    to_vote_count = None
    first_round_count = None
    second_round_count = None

    last_vote = None
    is_change_mode = False

    if type == Vote.TYPE_CHANGE:
        if change_child_name_id:
            try:
                child_name = ChildName.objects.get(id=change_child_name_id)
                last_score = None
                try:
                    last_vote = Vote.objects.get(child_name=child_name, child=active_child, user=request.user)
                    last_score = last_vote.score
                except Vote.DoesNotExist:
                    pass

                child_name.last_score = last_score
                is_change_mode = True
            except ChildName.DoesNotExist:
                return redirect(index_url)
        else:
            return redirect(index_url)
    else:
        all_names_count = ChildName.objects.filter(language=language_code, sex=active_child.sex).count()
        no_way_count, why_not_count, ranked_count, to_vote_count = \
            VoteHelper.get_vote_counts(request.user, active_child, all_names_count)

        if to_vote_count == 0:
            return redirect(index_url)

        first_round_count = to_vote_count - why_not_count
        second_round_count = why_not_count

        if (type == Vote.TYPE_FIRST_ROUND and first_round_count == 0) \
                or (type == Vote.TYPE_SECOND_ROUND and second_round_count == 0):
            return redirect(reverse('voter:vote', kwargs={'type': Vote.TYPE_RANDOM}))

        not_voted_names = ChildName.get_not_voted_list(user=request.user, child=active_child, vote_type=type)
        max_index = len(list(not_voted_names)) - 1
        child_name = not_voted_names[randint(0, max_index)]

    back_url = reverse('voter:vote', kwargs={'type': previous_type}) if is_step_back else index_url

    params = {
        'family': Family.get_by_user(request.user),
        'child_name': child_name,
        'total_count': to_vote_count,
        'first_round_count': first_round_count,
        'second_round_count': second_round_count,
        'active_child': active_child,
        'change_mode': is_change_mode,
        'last_vote': last_vote,
        'type': type,
        'previous_child_name_id': previous_child_name_id,
        'previous_type': previous_type,
        'back_url': back_url
    }

    return render(request, 'voter/vote.html', params)


def save(request):
    active_child_id = request.session.get(SessionHelper.KEY_ACTIVE_CHILD_ID, None)
    if not request.user.is_authenticated or request.method != 'POST' or active_child_id is None:
        return redirect(reverse('voter:index'))

    # to avoid double votes with re-post
    csrf.rotate_token(request)

    error = False

    score = request.POST.get('score', None)
    child_name_id = request.POST.get('child_name_id', None)
    vote_type = request.POST.get('vote_type', 'random')
    redirect_url = request.POST.get('redirect', reverse('voter:vote', kwargs={'type': vote_type}))

    if child_name_id is None or score is None or int(score) < -1 or int(score) > 6:
        error = True

    try:
        ChildName.objects.get(pk=child_name_id)
    except ChildName.DoesNotExist:
        # TODO error handling (display)
        error = True

    if not error:
        try:
            vote = Vote.objects.get(
                user_id=request.user.id,
                child_name_id=child_name_id,
                child_id=active_child_id,
            )
            vote.score = score
            vote.updated_at = timezone.now()
        except Vote.DoesNotExist:
            vote = Vote(
                score=score,
                user_id=request.user.id,
                child_name_id=child_name_id,
                child_id=active_child_id,
                created_at=timezone.now()
            )
        vote.save()

        VoteLog(
            score=score,
            user_id=request.user.id,
            child_name_id=child_name_id,
            child_id=active_child_id,
            created_at=timezone.now()
        ).save()

        if vote_type != Vote.TYPE_CHANGE:
            request.session[SessionHelper.KEY_LAST_VOTE_CHILD_NAME_ID] = child_name_id

    return redirect(redirect_url)

voter/templates/voter/index.html
{% extends 'voter/layout.html' %}

{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-default">
                <div class="panel-heading text-left">
                    <strong>{% trans 'Welcome' %}</strong>
                </div>
                <table class="table table-bordered">
                    <tr class="text-center">
                        <td>{% trans 'Logged in' %}<br/><strong>{{ request.user.username }}</strong></td>
                        <td>{% trans 'Family' %}<br/><strong>{{ family.last_name }}</strong></td>
                        <td>
                            {% trans 'Spouse' %}<br/>
                            <strong>{{ spouse.username }}</strong>
                            <span class="badge">{{ sps_to_vote_count }}</span>
                        </td>
                    </tr>
                </table>
                <div class="panel-footer text-center">
                    <form class="form-inline" method="post" action="{% url 'voter:child-change' %}">
                        {% csrf_token %}
                        <div class="input-group last-group">
                            <span class="input-group-addon">{% trans 'Child' %}</span>
                            <select
                                    name="selected_child_id"
                                    id="child-selector"
                                    class="form-control"
                                    title="{% trans 'Child' %}"
                            >
                                <option value="0">{% trans 'Please select the child!' %}</option>
                                {% for child in children %}
                                    <option
                                            value="{{ child.id }}"
                                            {% if request.session.active_child_id == child.id %}
                                                selected="selected"
                                            {% endif %}
                                    >{{ child.title }} - {{ child.get_sex_display }}</option>
                                {% endfor %}
                            </select>
                            <span class="input-group-btn">
                                <a
                                        href="#"
                                        class="btn btn-warning"
                                        data-toggle="modal"
                                        data-target="#childModal"
                                        role="button"
                                >
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </a>
                            </span>
                        </div>
                    </form>
                </div>

            </div>

            {% if request.session.active_child_id != None %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{% trans 'Progress' %}</strong>
                    </div>
                    <table class="table table-bordered">
                        <tr class="text-center">
                            <td>
                                {% trans 'Total' %}<br/>
                                <span class="label label-primary">{{ all_name_count }}</span>
                            </td>
                            <td>
                                {% trans 'No way!' %}<br/>
                                <span class="label label-danger">{{ my_no_way_count }}</span>
                            </td>
                            <td>
                                {% trans 'Why not?' %}<br/>
                                <span class="label label-warning">{{ my_why_not_count }}</span>
                            </td>
                            <td>
                                {% trans 'Ranked' %}<br/>
                                <span class="label label-success">{{ my_ranked_count }}</span>
                            </td>
                            <td>
                                {% trans 'Left' %}<br/>
                                <span class="label label-info">{{ my_to_vote_count }}</span>
                            </td>
                        </tr>
                    </table>
                    <div class="panel-body">
                        <h4>
                            {{ request.user.username }}
                            &nbsp;<small>{% blocktrans %}{{ my_to_vote_count }} names to go{% endblocktrans %}</small>
                        </h4>
                        <div class="progress">
                            <div
                                    class="progress-bar {% if my_progress == 100 %}progress-bar-success{% endif %}"
                                    role="progressbar"
                                    aria-valuenow="{{ my_progress }}"
                                    aria-valuemin="0"
                                    aria-valuemax="100"
                                    style="width: {{ my_progress}}%;"
                            >
                                {{ my_progress }}%
                            </div>
                        </div>
                        <h4>
                            {{ spouse.username }}
                            &nbsp;<small>{% blocktrans %}{{ sps_to_vote_count }} names to go{% endblocktrans %}</small>
                        </h4>
                        <div class="progress">
                            <div
                                    class="progress-bar {% if sps_progress == 100 %}progress-bar-success{% else %}progress-bar-warning{% endif %}"
                                    role="progressbar"
                                    aria-valuenow="{{ sps_progress }}"
                                    aria-valuemin="0"
                                    aria-valuemax="100"
                                    style="width: {{ sps_progress}}%;"
                            >
                                {{ sps_progress }}%
                            </div>
                        </div>
                    </div>
                    {% if my_to_vote_count > 0 %}
                        <div class="panel-footer text-center">
                            <a class="btn btn-success btn-lg" href="{% url 'voter:vote' type='random' %}" role="button">
                                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                {% trans 'Vote' %} <span class="badge">{{ my_to_vote_count }}</span>
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </div>

        {% if request.session.active_child_id != None %}
            <div class="col-md-7" id="result-container">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{% trans 'My Results' %}</strong>
                    </div>
                    <div class="panel-body">
                        {% include 'voter/block/my-results.html' %}
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{% trans 'Family Results' %}</strong>
                    </div>
                    <div class="panel-body">
                        {% include 'voter/block/family-results.html' %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>

    {% include 'voter/block/childform.html' %}
{% endblock %}

voter/templates/voter/layout.html
{% load static %}
{% load i18n %}
{% load main_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ BRAND }} - {% trans 'The best tool to choose the name!' %}</title>

    <link rel="shortcut icon" href="{% static 'voter/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'voter/images/favicon.ico' %}" type="image/x-icon">

    {% include 'voter/block/vendor.cdn.html' %}

    <link href="{% static 'voter/css/style.css' %}" rel="stylesheet">
    {% skin_css SKIN %}

    <script src="{% static 'voter/js/script.js' %}"></script>
</head>
<body class="child-{{ active_child.sex|lower }}">
    {% if YNAMER_ENV == 'production' %}
        {% include 'voter/block/analytics.html' %}
    {% endif %}

    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button
                            type="button"
                            class="navbar-toggle collapsed"
                            data-toggle="collapse"
                            data-target="#navbar-content"
                            aria-expanded="false"
                    >
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <strong>{{ BRAND }}</strong>
                    </a>
                    {% block header_fix_text %}{% endblock %}
                </div>

                <div class="collapse navbar-collapse" id="navbar-content">
                    <p class="navbar-text navbar-left">
                        {% block header_collapse_text %}
                            {% trans 'The best tool to choose the name!' %}
                        {% endblock %}
                    </p>
                    {% block header_content %}
                        <ul class="nav navbar-nav navbar-right">
                            {% if not request.user.is_anonymous and active_child and my_to_vote_count %}
                                <li>
                                    <a href="{% url 'voter:vote' type='random' %}">
                                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                                        &nbsp;{% trans 'Vote' %}
                                    </a>
                                </li>
                            {% endif %}
                            {% language_selector %}
                            {% skin_selector SKIN %}
                            {% if not request.user.is_anonymous %}
                                <li>
                                    <a href="{% url 'voter:logout' %}">
                                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                                        &nbsp;{% trans 'Logout' %}
                                    </a>
                                </li>
                            {% endif %}
                          </ul>
                    {% endblock %}
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}

        <h5 class="text-center"><small>norbert.lehotzky &copy; 2020 | {{ BUILD }}</small></h5>
    </div>
</body>
</html>

voter/templates/voter/login.html
{% extends 'voter/layout.html' %}

{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
            <form method="post" action="{% url 'voter:login' %}">
                {% csrf_token %}
                <div class="panel panel-default">
                    <div class="panel-heading text-left"><strong>{% trans 'Login' %}</strong></div>
                    <div class="panel-body">
                        {% if login_form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ login_form.non_field_errors }}
                            </div>
                        {% endif %}
                        {{ login_form.username.errors }}
                        <div class="input-group">
                            <span class="input-group-addon" id="login-username-icon">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            </span>
                            {{ login_form.username }}
                        </div>
                        {{ login_form.password.errors }}
                        <div class="input-group">
                            <span class="input-group-addon" id="login-password-icon">
                                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
                            </span>
                            {{ login_form.password }}
                        </div>
                    </div>
                    <div class="panel-footer text-center">
                        <button type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                            {% trans 'Submit' %}
                        </button>
                        <a class="btn btn-warning" role="button" href="{% url 'voter:signup' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                            {% trans 'Signup' %}
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}