voter/urls.py
from django.conf.urls import url, include

from voter.views import main, user, vote, asyncx

app_name = 'voter'

async_patterns = [
    url(r'^all-my-votes$', asyncx.get_all_my_votes, name='async-all-my-votes'),
    url(r'^all-names$', asyncx.get_all_names, name='async-all-names'),
    url(r'^my-best-names$', asyncx.get_my_best_names, name='async-my-best-names'),
    url(r'^common-best-names$', asyncx.get_common_best_names, name='async-common-best-names'),
    url(r'^common-total-names$', asyncx.get_common_total_names, name='async-common-total-names')
]

urlpatterns = [
    url(r'^$', main.index, name='index'),
    url(r'^login$', user.user_login, name='login'),
    url(r'^logout$', user.user_logout, name='logout'),
    url(r'^signup$', user.user_signup, name='signup'),
    url(r'^skin/change$', user.skin_change, name='skin-change'),
    url(r'^child/change$', user.child_change, name='child-change'),
    url(r'^child/save$', user.child_save, name='child-save'),
    url(r'^vote/(?P<type>first-round|second-round|random|change)$', vote.index, name='vote'),
    url(r'^vote/save$', vote.save, name='vote-save'),
    url(r'^async/', include(async_patterns)),
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

ynamer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('voter.urls')),
    url(r'^admin/', admin.site.urls),
]

voter/forms/child.py
from django import forms
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from voter.models import Child, Family


class ChildForm(forms.Form):
    family_id = forms.CharField(
        widget=forms.HiddenInput()
    )
    title = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Code name / title'),
                'aria-describedby': 'child-title-icon'
            }
        )
    )
    sex = forms.ChoiceField(
        choices=Child.SEX_TYPES,
        widget=forms.RadioSelect()
    )

    def save(self):
        child = Child(
            title=self.cleaned_data['title'],
            sex=self.cleaned_data['sex'],
            family=Family.objects.get(id=self.cleaned_data['family_id']),
            created_at=timezone.now()
        )
        child.save()

voter/forms/login.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from django import forms


class LoginForm(forms.Form):
    user = None
    username = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Username'),
                'aria-describedby': 'login-username-icon'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': _('Password'),
                'aria-describedby': 'login-password-icon'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        user = authenticate(
            username=cleaned_data['username'],
            password=cleaned_data['password']
        )
        if user is None:
            raise forms.ValidationError(_('User not found. Try again, or sign up!'))
        else:
            self.user = user

voter/views/asyncx.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from voter.models import Vote, VoteLog, ChildName, Child, Family
from voter.helpers.session import SessionHelper


def __init(request):
    response = None

    if not request.user.is_authenticated:
        response = HttpResponse('Unauthorized', status=401)

    active_child_id = request.session.get(SessionHelper.KEY_ACTIVE_CHILD_ID, None)
    if active_child_id is None:
        response = HttpResponse('Forbidden', status=403)

    return response is None, active_child_id, response


def get_my_best_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    my_best_names = Vote.objects.filter(
        user_id=request.user.id,
        score__gt=Vote.SCORE_WHY_NOT,
        child_id=active_child_id
    ).order_by('-score')

    params = {
        'my_best_names': my_best_names
    }

    return render_to_response('voter/async/my-best-names.html', params)


def get_all_my_votes(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    my_votes = VoteLog.objects.filter(user_id=request.user.id, child_id=active_child_id).order_by('-created_at')

    params = {
        'my_votes': my_votes
    }

    return render_to_response('voter/async/all-my-votes.html', params)


def get_all_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    active_child = Child.objects.get(id=active_child_id)
    all_names_with_score = ChildName.get_all_with_vote(user=request.user, child=active_child)

    params = {
        'names': all_names_with_score
    }

    return render_to_response('voter/async/all-names-with-score.html', params)


def get_common_best_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    active_child = Child.objects.get(id=active_child_id)
    family = Family.get_by_user(request.user)
    spouse = family.get_other_user(user=request.user)

    common_best_names = ChildName.get_common_best_list(user=request.user, spouse=spouse, child=active_child)

    params = {
        'common_best_names': common_best_names
    }

    return render_to_response('voter/async/common-best-names.html', params)


def get_common_total_names(request):
    is_valid, active_child_id, response = __init(request)
    if not is_valid:
        return response

    active_child = Child.objects.get(id=active_child_id)
    family = Family.get_by_user(request.user)
    spouse = family.get_other_user(user=request.user)

    common_total_names = ChildName.get_common_total_list(user=request.user, spouse=spouse, child=active_child)

    params = {
        'user': request.user,
        'spouse': spouse,
        'common_total_names': common_total_names
    }

    return render_to_response('voter/async/common-total-names.html', params)

voter/views/user.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout
from voter.models import Child, Family
from voter.forms.login import LoginForm
from voter.forms.signup import SignupForm
from voter.forms.child import ChildForm
from voter.helpers.session import SessionHelper
from voter.helpers.skin import SkinHelper
from voter.helpers.cookie import CookieHelper


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)

        if login_form.is_valid():
            login(request, login_form.user)
            return redirect(reverse('voter:index'))
    else:
        login_form = LoginForm()

    params = {
        'login_form': login_form
    }

    return render(request, 'voter/login.html', params)


def user_logout(request):
    logout(request)
    return redirect(reverse('voter:login'))


def user_signup(request):
    if request.method == 'POST':
        signup_form = SignupForm(request.POST)

        if signup_form.is_valid():
            signup_form.signup()
            # TODO implement success message
            return redirect(reverse('voter:login'))
    else:
        signup_form = SignupForm()

    params = {
        'signup_form': signup_form
    }

    return render(request, 'voter/signup.html', params)


def child_change(request):
    if request.method != 'POST' or not request.user.is_authenticated:
        return redirect(reverse('voter:index'))

    selected_child_id = request.POST.get('selected_child_id', None)
    family = Family.get_by_user(request.user)

    try:
        Child.objects.get(id=selected_child_id, family=family)
        request.session.update({
            SessionHelper.KEY_ACTIVE_CHILD_ID: int(selected_child_id)
        })
    except Child.DoesNotExist:
        # TODO error handling
        pass

    return redirect(reverse('voter:index'))


def child_save(request):
    if request.method != 'POST' or not request.user.is_authenticated:
        return redirect(reverse('voter:index'))

    child_form = ChildForm(request.POST)
    if child_form.is_valid():
        child_form.save()

    return redirect(reverse('voter:index'))


def skin_change(request):
    skin = request.GET.get('s', None)

    response = redirect(reverse('voter:index'))

    if skin in SkinHelper.AVAILABLE_SKINS:
        response.set_cookie(CookieHelper.KEY_SELECTED_SKIN, skin, CookieHelper.TTL_SELECTED_SKIN)

    return response

voter/views/vote.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.middleware import csrf
from random import randint
from voter.models import ChildName, Vote, Family, Child, VoteLog
from voter.helpers.vote import VoteHelper
from voter.helpers.session import SessionHelper


@csrf_exempt
def index(request, type=None):
    index_url = reverse('voter:index')

    active_child_id = request.session.get(SessionHelper.KEY_ACTIVE_CHILD_ID, None)
    language_code = request.session.get(SessionHelper.KEY_FAMILY_LANGUAGE_CODE, None)
    if not request.user.is_authenticated or active_child_id is None or language_code is None:
        return redirect(index_url)

    active_child = Child.objects.get(id=active_child_id)
    change_child_name_id = request.POST.get('child_name_id', None)
    is_step_back = bool(request.POST.get('step_back', False))
    previous_type = request.POST.get('previous_type', None)
    previous_child_name_id = request.session.get(SessionHelper.KEY_LAST_VOTE_CHILD_NAME_ID, None)

    if previous_child_name_id:
        del request.session[SessionHelper.KEY_LAST_VOTE_CHILD_NAME_ID]

    to_vote_count = None
    first_round_count = None
    second_round_count = None

    last_vote = None
    is_change_mode = False

    if type == Vote.TYPE_CHANGE:
        if change_child_name_id:
            try:
                child_name = ChildName.objects.get(id=change_child_name_id)
                last_score = None
                try:
                    last_vote = Vote.objects.get(child_name=child_name, child=active_child, user=request.user)
                    last_score = last_vote.score
                except Vote.DoesNotExist:
                    pass

                child_name.last_score = last_score
                is_change_mode = True
            except ChildName.DoesNotExist:
                return redirect(index_url)
        else:
            return redirect(index_url)
    else:
        all_names_count = ChildName.objects.filter(language=language_code, sex=active_child.sex).count()
        no_way_count, why_not_count, ranked_count, to_vote_count = \
            VoteHelper.get_vote_counts(request.user, active_child, all_names_count)

        if to_vote_count == 0:
            return redirect(index_url)

        first_round_count = to_vote_count - why_not_count
        second_round_count = why_not_count

        if (type == Vote.TYPE_FIRST_ROUND and first_round_count == 0) \
                or (type == Vote.TYPE_SECOND_ROUND and second_round_count == 0):
            return redirect(reverse('voter:vote', kwargs={'type': Vote.TYPE_RANDOM}))

        not_voted_names = ChildName.get_not_voted_list(user=request.user, child=active_child, vote_type=type)
        max_index = len(list(not_voted_names)) - 1
        child_name = not_voted_names[randint(0, max_index)]

    back_url = reverse('voter:vote', kwargs={'type': previous_type}) if is_step_back else index_url

    params = {
        'family': Family.get_by_user(request.user),
        'child_name': child_name,
        'total_count': to_vote_count,
        'first_round_count': first_round_count,
        'second_round_count': second_round_count,
        'active_child': active_child,
        'change_mode': is_change_mode,
        'last_vote': last_vote,
        'type': type,
        'previous_child_name_id': previous_child_name_id,
        'previous_type': previous_type,
        'back_url': back_url
    }

    return render(request, 'voter/vote.html', params)


def save(request):
    active_child_id = request.session.get(SessionHelper.KEY_ACTIVE_CHILD_ID, None)
    if not request.user.is_authenticated or request.method != 'POST' or active_child_id is None:
        return redirect(reverse('voter:index'))

    # to avoid double votes with re-post
    csrf.rotate_token(request)

    error = False

    score = request.POST.get('score', None)
    child_name_id = request.POST.get('child_name_id', None)
    vote_type = request.POST.get('vote_type', 'random')
    redirect_url = request.POST.get('redirect', reverse('voter:vote', kwargs={'type': vote_type}))

    if child_name_id is None or score is None or int(score) < -1 or int(score) > 6:
        error = True

    try:
        ChildName.objects.get(pk=child_name_id)
    except ChildName.DoesNotExist:
        # TODO error handling (display)
        error = True

    if not error:
        try:
            vote = Vote.objects.get(
                user_id=request.user.id,
                child_name_id=child_name_id,
                child_id=active_child_id,
            )
            vote.score = score
            vote.updated_at = timezone.now()
        except Vote.DoesNotExist:
            vote = Vote(
                score=score,
                user_id=request.user.id,
                child_name_id=child_name_id,
                child_id=active_child_id,
                created_at=timezone.now()
            )
        vote.save()

        VoteLog(
            score=score,
            user_id=request.user.id,
            child_name_id=child_name_id,
            child_id=active_child_id,
            created_at=timezone.now()
        ).save()

        if vote_type != Vote.TYPE_CHANGE:
            request.session[SessionHelper.KEY_LAST_VOTE_CHILD_NAME_ID] = child_name_id

    return redirect(redirect_url)

voter/templates/voter/block/analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90190704-1', 'auto');
  ga('send', 'pageview');
</script>

voter/templates/voter/block/childform.html
{% load i18n %}

<div class="modal fade" id="childModal" tabindex="-1" role="dialog" aria-labelledby="childModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <form method="post" action="{% url 'voter:child-save' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="childModalLabel">{% trans 'New child' %}</h4>
                </div>
                <div class="modal-body">
                    {{ child_form.title.errors }}
                    {{ child_form.family_id }}
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon" id="title-addon">
                            <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                        </span>
                        {{ child_form.title }}
                    </div>
                    {{ child_form.sex.errors }}
                    <div class="btn-group btn-group-justified" data-toggle="buttons">
                        <label class="btn btn-info btn-sm">
                            <input type="radio" name="sex" id="sex-boy" autocomplete="off" value="B">
                            <span class="glyphicon glyphicon-king" aria-hidden="true"></span>
                            &nbsp;&nbsp;<strong>{% trans 'Boy' %}</strong>
                        </label>
                        <label class="btn btn-danger btn-sm">
                            <input type="radio" name="sex" id="sex-girl" autocomplete="off" value="G">
                            <span class="glyphicon glyphicon-queen" aria-hidden="true"></span>
                            &nbsp;&nbsp;<strong>{% trans 'Girl' %}</strong>
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        {% trans 'Save' %}
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        {% trans 'Cancel' %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

voter/templates/voter/block/family-results.html
{% load i18n %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation">
        <a
                href="#common-best"
                aria-controls="common-best"
                role="tab"
                data-toggle="tab"
                data-async="{% url 'voter:async-common-best-names' %}"
        >
            <span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp;&nbsp;{% trans 'Common Best' %}
        </a>
    </li>
    <li role="presentation">
        <a
                href="#common-total"
                aria-controls="best-names"
                role="tab"
                data-toggle="tab"
                {% if common_total_active %}
                    data-async="{% url 'voter:async-common-total-names' %}"
                {% endif %}
        >
            <span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>&nbsp;&nbsp;{% trans 'Common Total' %}
        </a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content tab-scroll">
    <div role="tabpanel" class="tab-pane" id="common-best">
        <div class="async-loader table-info alert alert-info text-center">
            {% trans 'Loading...' %}
        </div>
        <div class="async-content"></div>
    </div>

    <div role="tabpanel" class="tab-pane" id="common-total">
        {% if common_total_active %}
            <div class="async-loader table-info alert alert-info text-center">
                {% trans 'Loading...' %}
            </div>
            <div class="async-content"></div>
        {% else %}
            <div class="alert alert-danger text-center table-info">
                {% trans 'This list is only available when both parents are done!' %}
            </div>
        {% endif %}
    </div>
</div>

voter/templates/voter/block/my-results.html
{% load i18n %}

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation">
        <a
                href="#best-names"
                aria-controls="best-names"
                role="tab"
                data-toggle="tab"
                data-async="{% url 'voter:async-my-best-names' %}"
        >
            <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>&nbsp;&nbsp;{% trans 'My Best Names' %}
        </a>
    </li>
    <li role="presentation">
        <a
                href="#all-my-votes"
                aria-controls="all-my-votes"
                role="tab"
                data-toggle="tab"
                data-async="{% url 'voter:async-all-my-votes' %}"
        >
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp;&nbsp;{% trans 'All My Votes' %}
        </a>
    </li>
    <li role="presentation">
        <a
                href="#all-names"
                aria-controls="all-names"
                role="tab"
                data-toggle="tab"
                data-async="{% url 'voter:async-all-names' %}"
        >
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>&nbsp;&nbsp;{% trans 'All Names' %}
        </a>
    </li>
</ul>

<!-- Tab panes -->
<div class="tab-content tab-scroll">
    <div role="tabpanel" class="tab-pane" id="best-names">
        <div class="async-loader table-info alert alert-info text-center">
            {% trans 'Loading...' %}
        </div>
        <div class="async-content"></div>
    </div>

    <div role="tabpanel" class="tab-pane" id="all-my-votes">
        <div class="async-loader table-info alert alert-info text-center">
            {% trans 'Loading...' %}
        </div>
        <div class="async-content"></div>
    </div>

    <div role="tabpanel" class="tab-pane" id="all-names">
        <div class="async-loader table-info alert alert-info text-center">
            {% trans 'Loading...' %}
        </div>
        <div class="async-content"></div>
    </div>
</div>

voter/templates/voter/block/vendor.cdn.html
<!-- jQuery -->
<script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"
></script>

<!-- Bootstrap: Latest compiled and minified JavaScript -->
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"
></script>